services:
  - type: web
    name: ojt-mysql-database
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: ojt_system
