services:
  - type: pserv
    name: ojt-mysql-database
    plan: starter
    env: docker
    docker:
      image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: ojt_system
